# Use root/123456 as user/password credentials
version: '3'
volumes:
  mysql_data:
    driver: local
services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/dockerfile
    volumes:
      - ./code/public:/var/www/html/public
    ports:
      - "80:80"

  php_fpm:
    build:
      context: .
      dockerfile: docker/php/dockerfile
    volumes:
      - ./code:/var/www/html

  php_cli:
    user: 1000:1000
    build:
      context: .
      dockerfile: docker/php_cli/dockerfile
    volumes:
      - ./code:/var/www/html

  database:
    build:
        context: .
        dockerfile: docker/database/dockerfile
    volumes:
      - ./database:/var/lib/mysql:rw
      - ./docker/database/config:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Example

  mariadb:
    image: mariadb
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    # Copy-pasted from https://github.com/docker-library/mariadb/issues/94
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: mariadb
      DB_ADDR: mariadb
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
    depends_on:
      - mariadb
